// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYG9ZlUtj2f0WefKiohRxCLgFBrYr4BFA',
    appId: '1:212745661813:web:e00c04c724c340acd6773c',
    messagingSenderId: '212745661813',
    projectId: 'hugspace-6b415',
    authDomain: 'hugspace-6b415.firebaseapp.com',
    databaseURL: 'https://hugspace-6b415-default-rtdb.firebaseio.com',
    storageBucket: 'hugspace-6b415.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVVnDmcjouSBuESE54uJ66mkUbCOluAM',
    appId: '1:212745661813:android:b1e58a2505400511d6773c',
    messagingSenderId: '212745661813',
    projectId: 'hugspace-6b415',
    databaseURL: 'https://hugspace-6b415-default-rtdb.firebaseio.com',
    storageBucket: 'hugspace-6b415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFnQLUpXNdI9ms3Ywuz31nW7aWz-8aGhE',
    appId: '1:212745661813:ios:4238e04f7357e912d6773c',
    messagingSenderId: '212745661813',
    projectId: 'hugspace-6b415',
    databaseURL: 'https://hugspace-6b415-default-rtdb.firebaseio.com',
    storageBucket: 'hugspace-6b415.firebasestorage.app',
    iosBundleId: 'com.khayelihle.hugspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFnQLUpXNdI9ms3Ywuz31nW7aWz-8aGhE',
    appId: '1:212745661813:ios:4238e04f7357e912d6773c',
    messagingSenderId: '212745661813',
    projectId: 'hugspace-6b415',
    databaseURL: 'https://hugspace-6b415-default-rtdb.firebaseio.com',
    storageBucket: 'hugspace-6b415.firebasestorage.app',
    iosBundleId: 'com.khayelihle.hugspace',
  );
}
